In [68]:
import torch as t
import numpy as np
import math
from torch import nn
from torchvision import datasets
import matplotlib.pyplot as plt
from torchvision.transforms import ToTensor
from torch.utils.data import DataLoader
import importlib

import nets.masked_autoencoder.model

Download CIFAR

In [25]:
cifar = datasets.CIFAR10(root="data", download=True, transform=ToTensor())
data_loader = DataLoader(cifar, batch_size=8, shuffle=True)
X, y = next(iter(data_loader))

Files already downloaded and verified


In [98]:
def reload_shit():
    importlib.reload(nets.masked_autoencoder.model)

In [103]:
reload_shit()
MAE = nets.masked_autoencoder.model.MaskedAutoEncoder
mae = MAE(img_size=32, patch_size=4)

Parameter containing:
tensor([[[ 0.0000,  0.0000,  0.0000,  ...,  1.0000,  1.0000,  1.0000],
         [ 0.8415,  0.8219,  0.8020,  ...,  1.0000,  1.0000,  1.0000],
         [ 0.9093,  0.9364,  0.9581,  ...,  1.0000,  1.0000,  1.0000],
         ...,
         [-0.9661,  0.7486,  0.2145,  ...,  1.0000,  1.0000,  1.0000],
         [-0.7392, -0.1185,  0.9115,  ...,  1.0000,  1.0000,  1.0000],
         [ 0.1674, -0.8836,  0.8744,  ...,  1.0000,  1.0000,  1.0000]]])


In [94]:
ree = mae(X)

In [28]:
ree.shape

torch.Size([8, 64, 512])

What do I need to do for embedding? 

In [46]:
r = t.tensor([[1, 2, 3], [4, 5, 56]])

In [47]:
r.repeat([1, 1])

tensor([[ 1,  2,  3],
        [ 4,  5, 56]])

In [48]:
w = t.tensor([1, 2, 3])

In [49]:
w + r

tensor([[ 2,  4,  6],
        [ 5,  7, 59]])

In [53]:
w = t.randn((2, 2, 3))

In [54]:
w

tensor([[[ 0.8868, -0.1843, -1.0674],
         [ 0.7272, -0.1691,  1.1926]],

        [[-2.9163,  2.1832,  0.3391],
         [ 0.7245,  0.9055, -1.4451]]])

In [59]:
w + t.tensor([[10,10, 10], [-10, -10, -10]])

tensor([[[ 10.8868,   9.8157,   8.9326],
         [ -9.2728, -10.1691,  -8.8074]],

        [[  7.0837,  12.1832,  10.3391],
         [ -9.2755,  -9.0945, -11.4451]]])

In [64]:
a = np.arange(10)

In [72]:
np.cos((64 / 10000) ** a)

array([0.54030231, 0.99997952, 1.        , 1.        , 1.        ,
       1.        , 1.        , 1.        , 1.        , 1.        ])

In [73]:
w

tensor([[[ 0.8868, -0.1843, -1.0674],
         [ 0.7272, -0.1691,  1.1926]],

        [[-2.9163,  2.1832,  0.3391],
         [ 0.7245,  0.9055, -1.4451]]])

In [75]:
t.concat([w, w], axis=1)

tensor([[[ 0.8868, -0.1843, -1.0674],
         [ 0.7272, -0.1691,  1.1926],
         [ 0.8868, -0.1843, -1.0674],
         [ 0.7272, -0.1691,  1.1926]],

        [[-2.9163,  2.1832,  0.3391],
         [ 0.7245,  0.9055, -1.4451],
         [-2.9163,  2.1832,  0.3391],
         [ 0.7245,  0.9055, -1.4451]]])

In [76]:
v = t.randn(10, 2)

In [77]:
v

tensor([[ 0.7175, -0.4684],
        [-1.9177,  2.0047],
        [ 0.1515,  0.2165],
        [-1.2575,  0.4641],
        [-0.5013,  1.0314],
        [ 0.4337,  1.4199],
        [-1.0745,  1.3987],
        [-0.2096,  0.3717],
        [-1.0850, -0.4827],
        [-0.9914,  0.1761]])

In [80]:
t.concat([v, v], axis=1)

tensor([[ 0.7175, -0.4684,  0.7175, -0.4684],
        [-1.9177,  2.0047, -1.9177,  2.0047],
        [ 0.1515,  0.2165,  0.1515,  0.2165],
        [-1.2575,  0.4641, -1.2575,  0.4641],
        [-0.5013,  1.0314, -0.5013,  1.0314],
        [ 0.4337,  1.4199,  0.4337,  1.4199],
        [-1.0745,  1.3987, -1.0745,  1.3987],
        [-0.2096,  0.3717, -0.2096,  0.3717],
        [-1.0850, -0.4827, -1.0850, -0.4827],
        [-0.9914,  0.1761, -0.9914,  0.1761]])

In [81]:
d = np.array(4)

In [84]:
t.tensor(d) + v

tensor([[4.7175, 3.5316],
        [2.0823, 6.0047],
        [4.1515, 4.2165],
        [2.7425, 4.4641],
        [3.4987, 5.0314],
        [4.4337, 5.4199],
        [2.9255, 5.3987],
        [3.7904, 4.3717],
        [2.9150, 3.5173],
        [3.0086, 4.1761]])

In [85]:
a = nn.Parameter(w)

In [91]:
a.data.copy_(t.zeros(2, 2, 3))

tensor([[[0., 0., 0.],
         [0., 0., 0.]],

        [[0., 0., 0.],
         [0., 0., 0.]]])

In [92]:
a

Parameter containing:
tensor([[[0., 0., 0.],
         [0., 0., 0.]],

        [[0., 0., 0.],
         [0., 0., 0.]]], requires_grad=True)

In [113]:
w

tensor([[[0., 0., 0.],
         [0., 0., 0.]],

        [[0., 0., 0.],
         [0., 0., 0.]]])

In [117]:
t.gather(w, 1, t.tensor([1, 1]).reshape(2, 2, 1))

RuntimeError: shape '[2, 2, 1]' is invalid for input of size 2